create database drozdovskiy;
use drozdovskiy;
create table BaseProduct (BaseProduct_ID integer not null, appearance integer,pr_name varchar(45), size integer, strength integer, thickness integer, weight integer, primary key (BaseProduct_ID));
create table hibernate_sequence (next_val bigint);
insert into hibernate_sequence values ( 1 );
insert into hibernate_sequence values ( 1 );
insert into hibernate_sequence values ( 1 );
insert into hibernate_sequence values ( 1 );
insert into hibernate_sequence values ( 1 );
create table Product (ProductID integer not null, appearance integer, size integer, strength integer, thickness integer, weight integer, Series_SeriesID integer, BaseProducts_BaseProductID integer, Series_Workers_workerID integer, primary key (ProductID));
create table Seria (SeriaID integer not null, date date, Users_UserID integer, Workers_workerID integer, primary key (SeriaID));
create table User (UserID integer not null, login varchar(45) unique, password varchar(45), role integer, primary key (UserID));
create table Worker (WorkerID integer not null, fio varchar(45),pr_name varchar(45), position varchar(45),otdel varchar(45), primary key (WorkerID));
alter table Product add constraint FKn96tqc0kk5m9tdfnem3r1xygq foreign key (Series_SeriesID) references Seria (SeriaID);
alter table Product add constraint FKj3btowylcqakk45bc42dvxkdn foreign key (BaseProducts_BaseProductID) references BaseProduct (BaseProduct_ID);
alter table Product add constraint FK45pewvoj4ntpmuecwovp0n3o foreign key (Series_Workers_workerID) references Worker (WorkerID);
alter table Seria add constraint FKgs12fwi9bvmuje95ejtorm8sc foreign key (Users_UserID) references User (UserID);
alter table Seria add constraint FK6s4h1q6n23m69v3dgrm65jt6v foreign key (Workers_workerID) references Worker (WorkerID);
INSERT INTO `baseproduct` VALUES (17,3,4,5,6,4,'Стул');
INSERT INTO `seria` VALUES (18,'2019-12-10',7,4);
INSERT INTO `user` VALUES (1,'Admin','1',0),(2,'User','user',1),(7,'Adminss','123',0);
INSERT INTO `worker` VALUES (4,'Пупкин В.О.','Слесарь','Тракторный'),(6,'Санаев В.С.','Менеджер','Маркетинговый'),(23,'Колов С.А.','Токарь','Тракторный');
INSERT INTO `product` VALUES (20,6,5,6,9,5,18,17,4,'Стул #1302'),(22,4,4,4,4,3,18,17,6,'Стул #1343');